# Generated by Django 5.0.6 on 2024-07-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
