# Generated by Django 5.0.6 on 2024-07-02 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AmenityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_key', models.CharField(max_length=50)),
                ('amenity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='core.amenity')),
            ],
        ),
    ]
