# Generated by Django 5.0.6 on 2024-07-03 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenityoption',
            name='type',
        ),
        migrations.AddField(
            model_name='amenityoption',
            name='amenity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.amenity'),
        ),
    ]
