# Generated by Django 5.0.6 on 2024-07-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='amenityoption',
            options={},
        ),
        migrations.AddField(
            model_name='amenity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='amenityoption',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
