# Generated by Django 5.0.6 on 2024-07-03 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_amenityoption_type_amenityoption_amenity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenityoption',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.amenity'),
        ),
    ]
