# Generated by Django 5.0.6 on 2024-07-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertyamenity',
            options={'verbose_name': 'Property amenity', 'verbose_name_plural': 'Property amenities'},
        ),
        migrations.AlterModelOptions(
            name='propertyimages',
            options={'verbose_name': 'Property image', 'verbose_name_plural': 'Property images'},
        ),
        migrations.AlterModelOptions(
            name='propertyoffers',
            options={'verbose_name': 'Property offer', 'verbose_name_plural': 'Property offers'},
        ),
        migrations.AddField(
            model_name='property',
            name='email_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
