# Generated by Django 5.0.6 on 2024-07-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.ImageField(upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
