# Generated by Django 5.0.6 on 2024-07-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='email_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
