# Generated by Django 5.0.6 on 2024-07-03 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_amenityoption_type_amenityoption_amenity'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='description_text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='whatsapp',
            new_name='whatsapp_number',
        ),
        migrations.RenameField(
            model_name='propertyimages',
            old_name='image_link',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='propertyoffers',
            old_name='offer_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='listing_purpose',
        ),
        migrations.RemoveField(
            model_name='propertyamenity',
            name='key',
        ),
        migrations.RemoveField(
            model_name='propertyoffers',
            name='offered_to',
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(related_name='amenities', to='properties.propertyamenity'),
        ),
        migrations.AddField(
            model_name='property',
            name='purpose',
            field=models.CharField(default='for sale', max_length=255),
        ),
        migrations.AddField(
            model_name='propertyamenity',
            name='amenity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.amenityoption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyimages',
            name='image',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='header',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='number_of_bath',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='number_of_bed',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(default='house', max_length=255),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='propertyoffers',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='properties.property'),
        ),
    ]
