# Generated by Django 5.0.6 on 2024-07-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
        migrations.AlterModelOptions(
            name='propertyamenity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='propertyimages',
            options={},
        ),
        migrations.AlterModelOptions(
            name='propertyoffers',
            options={},
        ),
        migrations.AddField(
            model_name='propertyamenity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertyimages',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertyoffers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
