# Generated by Django 5.0.6 on 2024-07-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_options_alter_propertyamenity_options_and_more'),
        ('properties', '0002_property_email_notification_sent_at'),
    ]

    operations = [
    ]
