# Generated by Django 5.0.6 on 2024-07-11 11:47

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_options_alter_propertyamenity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyoffers',
            name='state',
            field=django_fsm.FSMField(default='pending', max_length=50, protected=True),
        ),
    ]
