# Generated by Django 5.0.6 on 2024-07-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyamenity',
            name='value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
