# Generated by Django 5.0.6 on 2024-07-12 12:20

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertyoffers_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyoffers',
            name='state',
            field=django_fsm.FSMField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=50, protected=True),
        ),
    ]
